// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FFXIV
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ClassJobTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ClassJobTable GetRootAsClassJobTable(ByteBuffer _bb) { return GetRootAsClassJobTable(_bb, new ClassJobTable()); }
  public static ClassJobTable GetRootAsClassJobTable(ByteBuffer _bb, ClassJobTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClassJobTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FFXIV.ClassJob? ClassJobs(int j) { int o = __p.__offset(4); return o != 0 ? (FFXIV.ClassJob?)(new FFXIV.ClassJob()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ClassJobsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FFXIV.ClassJob? ClassJobsByKey(uint key) { int o = __p.__offset(4); return o != 0 ? FFXIV.ClassJob.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<FFXIV.ClassJobTable> CreateClassJobTable(FlatBufferBuilder builder,
      VectorOffset ClassJobsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ClassJobTable.AddClassJobs(builder, ClassJobsOffset);
    return ClassJobTable.EndClassJobTable(builder);
  }

  public static void StartClassJobTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddClassJobs(FlatBufferBuilder builder, VectorOffset ClassJobsOffset) { builder.AddOffset(0, ClassJobsOffset.Value, 0); }
  public static VectorOffset CreateClassJobsVector(FlatBufferBuilder builder, Offset<FFXIV.ClassJob>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateClassJobsVectorBlock(FlatBufferBuilder builder, Offset<FFXIV.ClassJob>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartClassJobsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FFXIV.ClassJobTable> EndClassJobTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.ClassJobTable>(o);
  }
  public static void FinishClassJobTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.ClassJobTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedClassJobTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.ClassJobTable> offset) { builder.FinishSizePrefixed(offset.Value); }
};

public struct ClassJob : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ClassJob GetRootAsClassJob(ByteBuffer _bb) { return GetRootAsClassJob(_bb, new ClassJob()); }
  public static ClassJob GetRootAsClassJob(ByteBuffer _bb, ClassJob obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClassJob __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Parent { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint JobIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string NameEn { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameEnBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameEnBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameEnArray() { return __p.__vector_as_array<byte>(10); }
  public string NameFr { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFrBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameFrBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameFrArray() { return __p.__vector_as_array<byte>(12); }
  public string NameDe { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameDeBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetNameDeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetNameDeArray() { return __p.__vector_as_array<byte>(14); }
  public string NameJa { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameJaBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetNameJaBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetNameJaArray() { return __p.__vector_as_array<byte>(16); }

  public static Offset<FFXIV.ClassJob> CreateClassJob(FlatBufferBuilder builder,
      uint Id = 0,
      uint Parent = 0,
      uint JobIndex = 0,
      StringOffset NameEnOffset = default(StringOffset),
      StringOffset NameFrOffset = default(StringOffset),
      StringOffset NameDeOffset = default(StringOffset),
      StringOffset NameJaOffset = default(StringOffset)) {
    builder.StartTable(7);
    ClassJob.AddNameJa(builder, NameJaOffset);
    ClassJob.AddNameDe(builder, NameDeOffset);
    ClassJob.AddNameFr(builder, NameFrOffset);
    ClassJob.AddNameEn(builder, NameEnOffset);
    ClassJob.AddJobIndex(builder, JobIndex);
    ClassJob.AddParent(builder, Parent);
    ClassJob.AddId(builder, Id);
    return ClassJob.EndClassJob(builder);
  }

  public static void StartClassJob(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, uint Id) { builder.AddUint(0, Id, 0); }
  public static void AddParent(FlatBufferBuilder builder, uint Parent) { builder.AddUint(1, Parent, 0); }
  public static void AddJobIndex(FlatBufferBuilder builder, uint JobIndex) { builder.AddUint(2, JobIndex, 0); }
  public static void AddNameEn(FlatBufferBuilder builder, StringOffset NameEnOffset) { builder.AddOffset(3, NameEnOffset.Value, 0); }
  public static void AddNameFr(FlatBufferBuilder builder, StringOffset NameFrOffset) { builder.AddOffset(4, NameFrOffset.Value, 0); }
  public static void AddNameDe(FlatBufferBuilder builder, StringOffset NameDeOffset) { builder.AddOffset(5, NameDeOffset.Value, 0); }
  public static void AddNameJa(FlatBufferBuilder builder, StringOffset NameJaOffset) { builder.AddOffset(6, NameJaOffset.Value, 0); }
  public static Offset<FFXIV.ClassJob> EndClassJob(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.ClassJob>(o);
  }

  public static VectorOffset CreateSortedVectorOfClassJob(FlatBufferBuilder builder, Offset<ClassJob>[] offsets) {
    Array.Sort(offsets, (Offset<ClassJob> o1, Offset<ClassJob> o2) => builder.DataBuffer.GetUint(Table.__offset(4, o1.Value, builder.DataBuffer)).CompareTo(builder.DataBuffer.GetUint(Table.__offset(4, o2.Value, builder.DataBuffer))));
    return builder.CreateVectorOfTables(offsets);
  }

  public static ClassJob? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = bb.GetUint(Table.__offset(4, bb.Length - tableOffset, bb)).CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new ClassJob().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};


}
