// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FFXIV
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ReputationTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ReputationTable GetRootAsReputationTable(ByteBuffer _bb) { return GetRootAsReputationTable(_bb, new ReputationTable()); }
  public static ReputationTable GetRootAsReputationTable(ByteBuffer _bb, ReputationTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReputationTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FFXIV.Reputation? Reputations(int j) { int o = __p.__offset(4); return o != 0 ? (FFXIV.Reputation?)(new FFXIV.Reputation()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ReputationsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FFXIV.Reputation? ReputationsByKey(uint key) { int o = __p.__offset(4); return o != 0 ? FFXIV.Reputation.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<FFXIV.ReputationTable> CreateReputationTable(FlatBufferBuilder builder,
      VectorOffset ReputationsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ReputationTable.AddReputations(builder, ReputationsOffset);
    return ReputationTable.EndReputationTable(builder);
  }

  public static void StartReputationTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddReputations(FlatBufferBuilder builder, VectorOffset ReputationsOffset) { builder.AddOffset(0, ReputationsOffset.Value, 0); }
  public static VectorOffset CreateReputationsVector(FlatBufferBuilder builder, Offset<FFXIV.Reputation>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateReputationsVectorBlock(FlatBufferBuilder builder, Offset<FFXIV.Reputation>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartReputationsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FFXIV.ReputationTable> EndReputationTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.ReputationTable>(o);
  }
  public static void FinishReputationTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.ReputationTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedReputationTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.ReputationTable> offset) { builder.FinishSizePrefixed(offset.Value); }
};

public struct Reputation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Reputation GetRootAsReputation(ByteBuffer _bb) { return GetRootAsReputation(_bb, new Reputation()); }
  public static Reputation GetRootAsReputation(ByteBuffer _bb, Reputation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Reputation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string NameEn { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameEnBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameEnBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameEnArray() { return __p.__vector_as_array<byte>(6); }
  public string NameFr { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFrBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameFrBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameFrArray() { return __p.__vector_as_array<byte>(8); }
  public string NameDe { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameDeBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameDeBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameDeArray() { return __p.__vector_as_array<byte>(10); }
  public string NameJa { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameJaBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameJaBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameJaArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<FFXIV.Reputation> CreateReputation(FlatBufferBuilder builder,
      uint Id = 0,
      StringOffset NameEnOffset = default(StringOffset),
      StringOffset NameFrOffset = default(StringOffset),
      StringOffset NameDeOffset = default(StringOffset),
      StringOffset NameJaOffset = default(StringOffset)) {
    builder.StartTable(5);
    Reputation.AddNameJa(builder, NameJaOffset);
    Reputation.AddNameDe(builder, NameDeOffset);
    Reputation.AddNameFr(builder, NameFrOffset);
    Reputation.AddNameEn(builder, NameEnOffset);
    Reputation.AddId(builder, Id);
    return Reputation.EndReputation(builder);
  }

  public static void StartReputation(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, uint Id) { builder.AddUint(0, Id, 0); }
  public static void AddNameEn(FlatBufferBuilder builder, StringOffset NameEnOffset) { builder.AddOffset(1, NameEnOffset.Value, 0); }
  public static void AddNameFr(FlatBufferBuilder builder, StringOffset NameFrOffset) { builder.AddOffset(2, NameFrOffset.Value, 0); }
  public static void AddNameDe(FlatBufferBuilder builder, StringOffset NameDeOffset) { builder.AddOffset(3, NameDeOffset.Value, 0); }
  public static void AddNameJa(FlatBufferBuilder builder, StringOffset NameJaOffset) { builder.AddOffset(4, NameJaOffset.Value, 0); }
  public static Offset<FFXIV.Reputation> EndReputation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.Reputation>(o);
  }

  public static VectorOffset CreateSortedVectorOfReputation(FlatBufferBuilder builder, Offset<Reputation>[] offsets) {
    Array.Sort(offsets, (Offset<Reputation> o1, Offset<Reputation> o2) => builder.DataBuffer.GetUint(Table.__offset(4, o1.Value, builder.DataBuffer)).CompareTo(builder.DataBuffer.GetUint(Table.__offset(4, o2.Value, builder.DataBuffer))));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Reputation? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = bb.GetUint(Table.__offset(4, bb.Length - tableOffset, bb)).CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new Reputation().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};


}
