// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FFXIV
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TitleTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TitleTable GetRootAsTitleTable(ByteBuffer _bb) { return GetRootAsTitleTable(_bb, new TitleTable()); }
  public static TitleTable GetRootAsTitleTable(ByteBuffer _bb, TitleTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TitleTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FFXIV.Title? Titles(int j) { int o = __p.__offset(4); return o != 0 ? (FFXIV.Title?)(new FFXIV.Title()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TitlesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FFXIV.Title? TitlesByKey(uint key) { int o = __p.__offset(4); return o != 0 ? FFXIV.Title.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<FFXIV.TitleTable> CreateTitleTable(FlatBufferBuilder builder,
      VectorOffset TitlesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    TitleTable.AddTitles(builder, TitlesOffset);
    return TitleTable.EndTitleTable(builder);
  }

  public static void StartTitleTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTitles(FlatBufferBuilder builder, VectorOffset TitlesOffset) { builder.AddOffset(0, TitlesOffset.Value, 0); }
  public static VectorOffset CreateTitlesVector(FlatBufferBuilder builder, Offset<FFXIV.Title>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTitlesVectorBlock(FlatBufferBuilder builder, Offset<FFXIV.Title>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTitlesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FFXIV.TitleTable> EndTitleTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.TitleTable>(o);
  }
  public static void FinishTitleTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.TitleTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedTitleTableBuffer(FlatBufferBuilder builder, Offset<FFXIV.TitleTable> offset) { builder.FinishSizePrefixed(offset.Value); }
};

public struct Title : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Title GetRootAsTitle(ByteBuffer _bb) { return GetRootAsTitle(_bb, new Title()); }
  public static Title GetRootAsTitle(ByteBuffer _bb, Title obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Title __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool IsPrefix { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string NameMasculineEn { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameMasculineEnBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameMasculineEnBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameMasculineEnArray() { return __p.__vector_as_array<byte>(8); }
  public string NameMasculineFr { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameMasculineFrBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameMasculineFrBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameMasculineFrArray() { return __p.__vector_as_array<byte>(10); }
  public string NameMasculineDe { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameMasculineDeBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameMasculineDeBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameMasculineDeArray() { return __p.__vector_as_array<byte>(12); }
  public string NameMasculineJa { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameMasculineJaBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetNameMasculineJaBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetNameMasculineJaArray() { return __p.__vector_as_array<byte>(14); }
  public string NameFeminineEn { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFeminineEnBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetNameFeminineEnBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetNameFeminineEnArray() { return __p.__vector_as_array<byte>(16); }
  public string NameFeminineFr { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFeminineFrBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetNameFeminineFrBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetNameFeminineFrArray() { return __p.__vector_as_array<byte>(18); }
  public string NameFeminineDe { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFeminineDeBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetNameFeminineDeBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetNameFeminineDeArray() { return __p.__vector_as_array<byte>(20); }
  public string NameFeminineJa { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameFeminineJaBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetNameFeminineJaBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetNameFeminineJaArray() { return __p.__vector_as_array<byte>(22); }

  public static Offset<FFXIV.Title> CreateTitle(FlatBufferBuilder builder,
      uint Id = 0,
      bool IsPrefix = false,
      StringOffset NameMasculineEnOffset = default(StringOffset),
      StringOffset NameMasculineFrOffset = default(StringOffset),
      StringOffset NameMasculineDeOffset = default(StringOffset),
      StringOffset NameMasculineJaOffset = default(StringOffset),
      StringOffset NameFeminineEnOffset = default(StringOffset),
      StringOffset NameFeminineFrOffset = default(StringOffset),
      StringOffset NameFeminineDeOffset = default(StringOffset),
      StringOffset NameFeminineJaOffset = default(StringOffset)) {
    builder.StartTable(10);
    Title.AddNameFeminineJa(builder, NameFeminineJaOffset);
    Title.AddNameFeminineDe(builder, NameFeminineDeOffset);
    Title.AddNameFeminineFr(builder, NameFeminineFrOffset);
    Title.AddNameFeminineEn(builder, NameFeminineEnOffset);
    Title.AddNameMasculineJa(builder, NameMasculineJaOffset);
    Title.AddNameMasculineDe(builder, NameMasculineDeOffset);
    Title.AddNameMasculineFr(builder, NameMasculineFrOffset);
    Title.AddNameMasculineEn(builder, NameMasculineEnOffset);
    Title.AddId(builder, Id);
    Title.AddIsPrefix(builder, IsPrefix);
    return Title.EndTitle(builder);
  }

  public static void StartTitle(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddId(FlatBufferBuilder builder, uint Id) { builder.AddUint(0, Id, 0); }
  public static void AddIsPrefix(FlatBufferBuilder builder, bool IsPrefix) { builder.AddBool(1, IsPrefix, false); }
  public static void AddNameMasculineEn(FlatBufferBuilder builder, StringOffset NameMasculineEnOffset) { builder.AddOffset(2, NameMasculineEnOffset.Value, 0); }
  public static void AddNameMasculineFr(FlatBufferBuilder builder, StringOffset NameMasculineFrOffset) { builder.AddOffset(3, NameMasculineFrOffset.Value, 0); }
  public static void AddNameMasculineDe(FlatBufferBuilder builder, StringOffset NameMasculineDeOffset) { builder.AddOffset(4, NameMasculineDeOffset.Value, 0); }
  public static void AddNameMasculineJa(FlatBufferBuilder builder, StringOffset NameMasculineJaOffset) { builder.AddOffset(5, NameMasculineJaOffset.Value, 0); }
  public static void AddNameFeminineEn(FlatBufferBuilder builder, StringOffset NameFeminineEnOffset) { builder.AddOffset(6, NameFeminineEnOffset.Value, 0); }
  public static void AddNameFeminineFr(FlatBufferBuilder builder, StringOffset NameFeminineFrOffset) { builder.AddOffset(7, NameFeminineFrOffset.Value, 0); }
  public static void AddNameFeminineDe(FlatBufferBuilder builder, StringOffset NameFeminineDeOffset) { builder.AddOffset(8, NameFeminineDeOffset.Value, 0); }
  public static void AddNameFeminineJa(FlatBufferBuilder builder, StringOffset NameFeminineJaOffset) { builder.AddOffset(9, NameFeminineJaOffset.Value, 0); }
  public static Offset<FFXIV.Title> EndTitle(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FFXIV.Title>(o);
  }

  public static VectorOffset CreateSortedVectorOfTitle(FlatBufferBuilder builder, Offset<Title>[] offsets) {
    Array.Sort(offsets, (Offset<Title> o1, Offset<Title> o2) => builder.DataBuffer.GetUint(Table.__offset(4, o1.Value, builder.DataBuffer)).CompareTo(builder.DataBuffer.GetUint(Table.__offset(4, o2.Value, builder.DataBuffer))));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Title? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = bb.GetUint(Table.__offset(4, bb.Length - tableOffset, bb)).CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new Title().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};


}
