<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\lib\flatbuffers\net\FlatBuffers\FlatBuffers.csproj" />
      <ProjectReference Include="..\NetStone\NetStone.csproj" />
    </ItemGroup>

</Project>
